version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - 32769:27017
    networks:
      - appandmongo

  application:
    image: antmog/docker-demo:6
    container_name: app
    hostname: app
    ports:
      - 8087:8082
    networks:
      - appandmongo

networks:
  appandmongo:
    driver: bridge
